pipeline:
  name: DEVOPS - PYTHON CONTAINER BASED APPLICATION
  identifier: DEVOPS_PYTHON_CONTAINER_BASED_APPLICATION
  projectIdentifier: grand_line
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        repoName: harness
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
            key: ""
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: Code Quality and Security
                  identifier: Code_Quality_and_Security
                  template:
                    templateRef: Code_Security
                    versionLabel: v1.0.0
                    gitBranch: main
                    templateInputs:
                      variables:
                        - name: WORKSPACE
                          type: String
                          value: <+input>
                        - name: SONAR_PROJECT_KEY
                          type: String
                          value: <+input>
              - stepGroup:
                  name: Python Checks
                  identifier: Python_Checks
                  template:
                    templateRef: Python_Specific_Validation
                    versionLabel: v1.0.0
                    templateInputs:
                      variables:
                        - name: WORKSPACE
                          type: String
                          value: <+input>
              - stepGroup:
                  name: Build Sign And Push
                  identifier: Build_Sign_And_Push
                  template:
                    templateRef: Build_Sign_Scan
                    versionLabel: v1.0.0
                    gitBranch: main
                    templateInputs:
                      variables:
                        - name: WORKSPACE
                          type: String
                          value: <+input>
                        - name: DOCKER_REPOSITORY
                          type: String
                          value: <+input>
        sendGitStatus:
          enabled: false
          name: DevOps - Continuos Integration ( Quality, Security, Language Checks and Build Validation )
