pipeline:
  name: DEVOPS - GOLANG APPLICATIONS
  identifier: DEVOPS_GOLANG_APPLICATIONS
  tags: {}
  template:
    templateRef: DevOps_Container_Based_Pipeline
    versionLabel: v1.0.0-
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: Build_and_Package
            type: CI
            spec:
              execution:
                steps:
                  - stepGroup:
                      identifier: Code_Security
                      template:
                        templateInputs:
                          variables:
                            - name: WORKSPACE
                              type: String
                              value: <+input>
                            - name: SONAR_PROJECT_KEY
                              type: String
                              value: <+input>
                  - stepGroup:
                      identifier: Build_Sing_and_Scan
                      template:
                        templateInputs:
                          variables:
                            - name: WORKSPACE
                              type: String
                              value: <+input>
                            - name: DOCKER_REPOSITORY
                              type: String
                              value: <+input>
  projectIdentifier: grand_line
  orgIdentifier: default
